# yaml-language-server: $schema=https://raw.githubusercontent.com/readthedocs/readthedocs.org/master/readthedocs/rtd_tests/fixtures/spec/v2/schema.json
version: 2

python:
  install:
    - requirements: requirements.txt

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
  jobs:
    # ref: <https://docs.readthedocs.io/en/stable/build-customization.html#unshallow-git-clone>
    post_checkout:
      - git fetch --unshallow || true
    pre_install:
      - pip install uv
      - uv export --all-extras --group docs --no-hashes --output-file requirements.txt

mkdocs:
  configuration: mkdocs.yaml
