# This file is @generated by templates/array_types/numpy/_bool.py.jinja.
# Do not edit.
import numpy as np
from jaxtyping import Bool

B = Bool[np.ndarray, ""]
BN = Bool[np.ndarray, "N"]
B33 = Bool[np.ndarray, "33"]
B34 = Bool[np.ndarray, "34"]
B43 = Bool[np.ndarray, "43"]
B44 = Bool[np.ndarray, "44"]
BMN = Bool[np.ndarray, "MN"]
BN3 = Bool[np.ndarray, "N3"]
BNN = Bool[np.ndarray, "NN"]
