# This file is @generated by templates/array_types/numpy/_float.py.jinja.
# Do not edit.
import numpy as np
from jaxtyping import Float

F = Float[np.ndarray, ""]
FN = Float[np.ndarray, "N"]
F33 = Float[np.ndarray, "33"]
F34 = Float[np.ndarray, "34"]
F43 = Float[np.ndarray, "43"]
F44 = Float[np.ndarray, "44"]
FMN = Float[np.ndarray, "MN"]
FN3 = Float[np.ndarray, "N3"]
FNN = Float[np.ndarray, "NN"]
