# This file is @generated by templates/array_types/numpy/_integer.py.jinja.
# Do not edit.
import numpy as np
from jaxtyping import Integer

I = Integer[np.ndarray, ""]
IN = Integer[np.ndarray, "N"]
I33 = Integer[np.ndarray, "33"]
I34 = Integer[np.ndarray, "34"]
I43 = Integer[np.ndarray, "43"]
I44 = Integer[np.ndarray, "44"]
IMN = Integer[np.ndarray, "MN"]
IN3 = Integer[np.ndarray, "N3"]
INN = Integer[np.ndarray, "NN"]
