# This file is @generated by templates/array_types/torch/_bool.py.jinja.
# Do not edit.
import torch
from jaxtyping import Bool

B = Bool[torch.Tensor, ""]
BN = Bool[torch.Tensor, "N"]
B33 = Bool[torch.Tensor, "33"]
B34 = Bool[torch.Tensor, "34"]
B43 = Bool[torch.Tensor, "43"]
B44 = Bool[torch.Tensor, "44"]
BMN = Bool[torch.Tensor, "MN"]
BN3 = Bool[torch.Tensor, "N3"]
BNN = Bool[torch.Tensor, "NN"]
