# This file is @generated by templates/array_types/torch/_float.py.jinja.
# Do not edit.
import torch
from jaxtyping import Float

F = Float[torch.Tensor, ""]
FN = Float[torch.Tensor, "N"]
F33 = Float[torch.Tensor, "33"]
F34 = Float[torch.Tensor, "34"]
F43 = Float[torch.Tensor, "43"]
F44 = Float[torch.Tensor, "44"]
FMN = Float[torch.Tensor, "MN"]
FN3 = Float[torch.Tensor, "N3"]
FNN = Float[torch.Tensor, "NN"]
