# This file is @generated by templates/array_types/torch/_integer.py.jinja.
# Do not edit.
import torch
from jaxtyping import Integer

I = Integer[torch.Tensor, ""]
IN = Integer[torch.Tensor, "N"]
I33 = Integer[torch.Tensor, "33"]
I34 = Integer[torch.Tensor, "34"]
I43 = Integer[torch.Tensor, "43"]
I44 = Integer[torch.Tensor, "44"]
IMN = Integer[torch.Tensor, "MN"]
IN3 = Integer[torch.Tensor, "N3"]
INN = Integer[torch.Tensor, "NN"]
