# This file is @generated by templates/array_types/array/_bool.py.jinja.
# Do not edit.
from jaxtyping import Bool

from qtk.array_types import ArrayLike

BLike = Bool[ArrayLike, ""]
BNLike = Bool[ArrayLike, "N"]
B33Like = Bool[ArrayLike, "33"]
B34Like = Bool[ArrayLike, "34"]
B43Like = Bool[ArrayLike, "43"]
B44Like = Bool[ArrayLike, "44"]
BMNLike = Bool[ArrayLike, "MN"]
BN3Like = Bool[ArrayLike, "N3"]
BNNLike = Bool[ArrayLike, "NN"]
