# This file is @generated by templates/array_types/array/_float.py.jinja.
# Do not edit.
from jaxtyping import Float

from qtk.array_types import ArrayLike

FLike = Float[ArrayLike, ""]
FNLike = Float[ArrayLike, "N"]
F33Like = Float[ArrayLike, "33"]
F34Like = Float[ArrayLike, "34"]
F43Like = Float[ArrayLike, "43"]
F44Like = Float[ArrayLike, "44"]
FMNLike = Float[ArrayLike, "MN"]
FN3Like = Float[ArrayLike, "N3"]
FNNLike = Float[ArrayLike, "NN"]
