# This file is @generated by templates/array_types/array/_integer.py.jinja.
# Do not edit.
from jaxtyping import Integer

from qtk.array_types import ArrayLike

ILike = Integer[ArrayLike, ""]
INLike = Integer[ArrayLike, "N"]
I33Like = Integer[ArrayLike, "33"]
I34Like = Integer[ArrayLike, "34"]
I43Like = Integer[ArrayLike, "43"]
I44Like = Integer[ArrayLike, "44"]
IMNLike = Integer[ArrayLike, "MN"]
IN3Like = Integer[ArrayLike, "N3"]
INNLike = Integer[ArrayLike, "NN"]
