# This file is @generated by templates/array_types/jax/_bool.py.jinja.
# Do not edit.
import jax
from jaxtyping import Bool

B = Bool[jax.Array, ""]
BN = Bool[jax.Array, "N"]
B33 = Bool[jax.Array, "33"]
B34 = Bool[jax.Array, "34"]
B43 = Bool[jax.Array, "43"]
B44 = Bool[jax.Array, "44"]
BMN = Bool[jax.Array, "MN"]
BN3 = Bool[jax.Array, "N3"]
BNN = Bool[jax.Array, "NN"]
