# This file is @generated by templates/array_types/jax/_float.py.jinja.
# Do not edit.
import jax
from jaxtyping import Float

F = Float[jax.Array, ""]
FN = Float[jax.Array, "N"]
F33 = Float[jax.Array, "33"]
F34 = Float[jax.Array, "34"]
F43 = Float[jax.Array, "43"]
F44 = Float[jax.Array, "44"]
FMN = Float[jax.Array, "MN"]
FN3 = Float[jax.Array, "N3"]
FNN = Float[jax.Array, "NN"]
