# This file is @generated by templates/array_types/jax/_integer.py.jinja.
# Do not edit.
import jax
from jaxtyping import Integer

I = Integer[jax.Array, ""]
IN = Integer[jax.Array, "N"]
I33 = Integer[jax.Array, "33"]
I34 = Integer[jax.Array, "34"]
I43 = Integer[jax.Array, "43"]
I44 = Integer[jax.Array, "44"]
IMN = Integer[jax.Array, "MN"]
IN3 = Integer[jax.Array, "N3"]
INN = Integer[jax.Array, "NN"]
